language: python

python:
  - "3.8"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=irwin setup.py test

after_success:
  - coveralls

before_deploy:
  - git clean -dfx

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "chKSBfNJ9oinqpKZAXvtVlMuvMw6U2UQRaXYM1KCv8FExqqljhV6g4t8rWJdD08L4HXvGq7dcqABsVLGEdtpt4Q7hhoFzdpeGWBLZurjt2mMwFvbwg3zlczM/PvMEA2wS7oVe9gU5wkwu+p9X0x2RC3X5CYyT6KtHutHD4tvxixN7c0ZtbWZM7gpLm+5zCdIcKSlq/aMXxN8eQL2vTfsx8K2LaEANw74bE0R9NPj/L9/tEnxtneM2ulFovFcFdaB0UB5RJZh5P5S/Z9nv1D2YzeImqjdjnawT2dBVzDj9hLN3aW67E9wiRJwZYGlxJwJqoJnrWapc6yI0Nkjr5R9YK3U08w3ISbUxRg9pFDhMloeWXAsL0/ZWC5U+Qhfb21hhgJ4XonN8/Val/c14bIwN7Ng7zghgwEnfZfeSOyCfTY/aFOSFzbkH+k4IYgbpLRVPt6we4TaI9xk68GJPbd+bfHXL+NC2ME+lx4+dJY8JOA2++3lMk+VYdnSyCS0MqUtk/YBG8TKKLWt7ipGzRTrtylYVdg/dFk6P65q65rKGU1F7XZIzxRiY7NkuCkMxfBqcUTnKlYCAaV78qejKOaIWtvL1U5NgJOjkJrRZpN1bd3Zdj1LDp2JL1dXJYlTZz0xLfXmvIaIe3jM3Jomg7kwklogXMsOL8IzxpRAdmGpv1M="
  edge: true
  skip_existing: true
  on:
    tags: true
